### ISSUE TITLE
运行后，无法直接修改代码

### ISSUE THREAD

**Issue by wweggplant** [baabaaox/ScrapyDouban#15]
[这里](https://github.com/baabaaox/ScrapyDouban/blob/cb655669c25bb85d6a74737d16e5f9760654ed71/docker/scrapy/Dockerfile#L9) 能否改成映射到本地文件？发现之前的代码docker运行起来后，改配置要到进到docker中去改。不知道我说的对不对

```
RUN apk add --update --no-cache gcc musl-dev libffi-dev libxml2-dev libxslt-dev jpeg-dev curl-dev make python3 
.........
&& mkdir /srv/ScrapyDouban
# && git clone https://github.com/baabaaox/ScrapyDouban.git /srv/ScrapyDouban
```

**Comment by baabaaox** [comment]
@wweggplant 可以代码 clone 下来后，修改一下 docker-compose.yml 文件，根据个人项目的路径来映射

scrapy:
  build: ./scrapy
  container_name: douban_scrapy
  volumes:
    - 本地路径:映射路径
  links:
    - "db"
  tty: true
