### ISSUE TITLE
怎么定制自己的subject id list? 

### ISSUE THREAD

**Issue by MicMiao** [baabaaox/ScrapyDouban#20]
你好！我想问一个非常菜鸟的问题。
我有200个书籍的subject ID 在一个csv文件。 我可以把它上传到mysql里。 因为我想爬这些书的数据。 但是我在执行scrapy list，和 scrapy crawl book_subject 的时候发现，爬的subject ID并不是我想要的。 我不知道这些subject ID是从哪里来的？ 我在哪里可以定制自己的subject ID list？ 

多谢了！！

michele

**Comment by baabaaox** [comment]
@MicMiao 
book_subject 是收集书籍 subject_id 的，收集到的 subject_id 放到 subjects 这张表里面 type 标记成 book。
所以你要自定义的直接把 subject ID 导入到 subjects 这张表里面。
```
INSERT INTO `subjects` (`douban_id`, `type`) VALUES
(1292721, 'book'),
(3733492, 'book');
```
然后执行 scrapy crawl book_meta 收集书籍信息。

豆瓣反爬虫反得厉害，你没挂代理的话设置 [settings.py](https://github.com/baabaaox/ScrapyDouban/blob/b6d2cced7fc163ede4df560dac1f8dfa218a59b5/scrapy/douban/settings.py#L27) 下面俩个参数，控制一下爬取的速度，200个应该没问题。
```
CONCURRENT_REQUESTS = 1
DOWNLOAD_DELAY = 3
```

**Comment by MicMiao** [comment]
太谢谢了！ 问题已经解决了。 唯一一个好奇的地方是“ 收集书籍评论” 也就是comment, 是不是设置了只能爬5个评论？ 有没有可能手动改这个数字？ 还是因为有其他客观的限制存在？

**Comment by baabaaox** [comment]
@MicMiao 

修改 [book_comment.py](https://github.com/baabaaox/ScrapyDouban/blob/b6d2cced7fc163ede4df560dac1f8dfa218a59b5/scrapy/douban/spiders/book_comment.py#L19)

```python
baseurl = "https://m.douban.com/rexxar/api/v2/book/%s/interests?count=5&order_by=hot"
// 改成
baseurl = "https://m.douban.com/rexxar/api/v2/book/%s/interests?count=50&order_by=hot"
```
这个只是第一页的数据，单页最多只能返回50条数据，如果需要更多要自己去看看分页参数是什么

**Comment by MicMiao** [comment]
Thanks a lot!
